name: sim_info
description: A Flutter plugin to retrieve SIM information
version: 0.1.4
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: flutter.moum.sim_info
        pluginClass: SimInfoPlugin
      ios:
        pluginClass: SimInfoPlugin
